# name: eco_drive
# description: A new Flutter project.

# publish_to: 'none' 

# version: 1.0.0+1

# environment:
#   sdk: '>=3.1.3 <4.0.0'

# #
#   flutter:
#     sdk: flutter


#   cupertino_icons: ^1.0.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^2.0.0


# flutter:


#   uses-material-design: true


name: eco_drive
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sensors: ^2.0.3  # Added the sensors package 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  